openapi: 3.0.0
info:
  title: Login API
  version: 1.0.0
  description: API for user authentication.

servers:
  - url: 'http://127.0.0.1:5000'
    description: Localhost server

paths:
  /register:
    put:
      summary: Register new user.
      operationId: register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - email
                - password
              properties:
                username:
                  type: string
                  description: The user's username.
                  example: johndoe
                email:
                  type: string
                  description: The user's email address.
                  example: johndoe@example.com
                password:
                  type: string
                  description: The user's password.
                  example: '123456'
              additionalProperties: false
      responses:
        201:
          description: User successfully created.
        400:
          description: Bad request, one or more parameters are empty or missing.
        500:
          description: Internal Server Error.
